//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1PrograII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_NotasEstudiante
    {
        public int Id { get; set; }
        public string NombreEstudiante { get; set; }
        public Nullable<double> Lab1 { get; set; }
        public Nullable<double> Lab2 { get; set; }
        public Nullable<double> Lab3 { get; set; }
        public Nullable<double> Par1 { get; set; }
        public Nullable<double> Par2 { get; set; }
        public Nullable<double> Par3 { get; set; }
    }
}
